-- JamIssue Supabase / Postgres schema
-- 2026-03-18 湲곗? ?뺢퇋?붾맂 ?ㅽ궎留?
-- ?듭떖 洹쒖튃:
-- 1. user_stamp??諛⑸Ц 濡쒓렇 ?뚯씠釉붿씠硫??좎쭨媛 ?ㅻⅤ硫?媛숈? ?μ냼???ㅼ떆 ?곷┰?????덈떎.
-- 2. stamp_id媛 ?덉뼱???꾧린(feed)瑜??묒꽦?????덈떎.
-- 3. 24?쒓컙 ?대궡???곗냽 ?ㅽ꺃?꾨뒗 媛숈? travel_session?쇰줈 臾띕뒗??
-- 4. user_route??媛쒕컻???먮젅?댁뀡 肄붿뒪? ?ъ슜???앹꽦 寃쎈줈瑜??④퍡 ?대릺, is_user_generated濡?援щ텇?쒕떎.

create table if not exists public."user" (
  user_id varchar(64) primary key,
  email varchar(255),
  nickname varchar(100) not null,
  provider varchar(50) not null default 'demo',
  profile_completed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists idx_user_provider on public."user"(provider);
create unique index if not exists uq_user_nickname_lower on public."user"(lower(nickname));

create table if not exists public.user_identity (
  identity_id integer generated by default as identity primary key,
  user_id varchar(64) not null references public."user"(user_id) on delete cascade,
  provider varchar(50) not null,
  provider_user_id varchar(120) not null,
  email varchar(255),
  profile_image varchar(255),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint uq_user_identity_provider_user unique (provider, provider_user_id),
  constraint uq_user_identity_user_provider unique (user_id, provider)
);
create index if not exists idx_user_identity_user_id on public.user_identity(user_id);

create table if not exists public.map (
  position_id integer generated by default as identity primary key,
  slug varchar(100) not null unique,
  name varchar(120) not null,
  district varchar(50) not null,
  category varchar(20) not null,
  latitude double precision not null,
  longitude double precision not null,
  summary varchar(255) not null,
  description text not null,
  image_url varchar(255),
  image_storage_path varchar(255),
  vibe_tags jsonb not null default '[]'::jsonb,
  visit_time varchar(50) not null,
  route_hint varchar(255) not null,
  stamp_reward varchar(120) not null,
  hero_label varchar(60) not null,
  jam_color varchar(20) not null,
  accent_color varchar(20) not null,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists idx_map_category on public.map(category);
create index if not exists idx_map_active_name on public.map(is_active, name);

create table if not exists public.public_data_source (
  source_id integer generated by default as identity primary key,
  source_key varchar(80) not null unique,
  provider varchar(40) not null,
  name varchar(120) not null,
  source_url varchar(255),
  last_imported_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.public_place (
  public_place_id integer generated by default as identity primary key,
  source_id integer not null references public.public_data_source(source_id),
  external_id varchar(120) not null,
  map_slug varchar(100) not null,
  display_name varchar(140) not null,
  district varchar(50) not null,
  category varchar(20) not null,
  address varchar(255),
  road_address varchar(255),
  latitude double precision,
  longitude double precision,
  summary varchar(255) not null default '',
  description text not null default '',
  image_url varchar(255),
  contact varchar(100),
  source_page_url varchar(255),
  source_updated_at timestamptz,
  sync_status varchar(20) not null default 'imported',
  raw_payload jsonb not null default '{}'::jsonb,
  normalized_payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint uq_public_place_source_external unique (source_id, external_id)
);
create index if not exists idx_public_place_map_slug on public.public_place(map_slug);
create index if not exists idx_public_place_sync_status on public.public_place(sync_status);

create table if not exists public.public_place_map_link (
  public_place_map_link_id integer generated by default as identity primary key,
  public_place_id integer not null references public.public_place(public_place_id),
  position_id integer not null references public.map(position_id),
  match_method varchar(30) not null default 'slug',
  confidence_score double precision not null default 1.0,
  is_primary boolean not null default true,
  linked_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint uq_public_place_map_link unique (public_place_id, position_id)
);
create index if not exists idx_public_place_map_link_position on public.public_place_map_link(position_id);

create table if not exists public.public_event (
  public_event_id integer generated by default as identity primary key,
  source_id integer not null references public.public_data_source(source_id),
  external_id varchar(120) not null,
  title varchar(160) not null,
  venue_name varchar(140),
  district varchar(50) not null default '',
  address varchar(255),
  road_address varchar(255),
  latitude double precision,
  longitude double precision,
  starts_at timestamptz not null,
  ends_at timestamptz not null,
  summary varchar(255) not null default '',
  description text not null default '',
  image_url varchar(255),
  contact varchar(100),
  source_page_url varchar(255),
  source_updated_at timestamptz,
  sync_status varchar(20) not null default 'imported',
  raw_payload jsonb not null default '{}'::jsonb,
  normalized_payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint uq_public_event_source_external unique (source_id, external_id)
);
create index if not exists idx_public_event_dates on public.public_event(starts_at, ends_at);
create index if not exists idx_public_event_status on public.public_event(sync_status);

create table if not exists public.public_event_map_link (
  public_event_map_link_id integer generated by default as identity primary key,
  public_event_id integer not null references public.public_event(public_event_id),
  position_id integer not null references public.map(position_id),
  match_method varchar(30) not null default 'name-exact',
  confidence_score double precision not null default 1.0,
  is_primary boolean not null default true,
  linked_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint uq_public_event_map_link unique (public_event_id, position_id)
);
create index if not exists idx_public_event_map_link_position on public.public_event_map_link(position_id);

create table if not exists public.travel_session (
  travel_session_id integer generated by default as identity primary key,
  user_id varchar(64) not null references public."user"(user_id) on delete cascade,
  started_at timestamptz not null,
  ended_at timestamptz not null,
  last_stamp_at timestamptz not null,
  stamp_count integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists idx_travel_session_user_id on public.travel_session(user_id);
create index if not exists idx_travel_session_last_stamp_at on public.travel_session(last_stamp_at);

create table if not exists public.user_stamp (
  stamp_id integer generated by default as identity primary key,
  user_id varchar(64) not null references public."user"(user_id) on delete cascade,
  position_id integer not null references public.map(position_id),
  travel_session_id integer references public.travel_session(travel_session_id) on delete set null,
  stamp_date date not null,
  visit_ordinal integer not null default 1,
  created_at timestamptz not null default now(),
  constraint uq_user_stamp_per_day unique (user_id, position_id, stamp_date)
);
create index if not exists idx_user_stamp_position_id on public.user_stamp(position_id);
create index if not exists idx_user_stamp_travel_session_id on public.user_stamp(travel_session_id);
create index if not exists idx_user_stamp_user_created_at on public.user_stamp(user_id, created_at);

create table if not exists public.feed (
  feed_id integer generated by default as identity primary key,
  position_id integer not null references public.map(position_id),
  user_id varchar(64) not null references public."user"(user_id) on delete cascade,
  stamp_id integer not null references public.user_stamp(stamp_id),
  body text not null,
  mood varchar(20) not null,
  badge varchar(50) not null default '濡쒖뺄 硫붾え',
  image_url varchar(255),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists idx_feed_position_id on public.feed(position_id);
create index if not exists idx_feed_user_id on public.feed(user_id);
create index if not exists idx_feed_stamp_id on public.feed(stamp_id);

create table if not exists public.feed_like (
  feed_like_id integer generated by default as identity primary key,
  feed_id integer not null references public.feed(feed_id) on delete cascade,
  user_id varchar(64) not null references public."user"(user_id) on delete cascade,
  created_at timestamptz not null default now(),
  constraint uq_feed_like unique (feed_id, user_id)
);
create index if not exists idx_feed_like_user_id on public.feed_like(user_id);

create table if not exists public.user_comment (
  comment_id integer generated by default as identity primary key,
  feed_id integer not null references public.feed(feed_id) on delete cascade,
  user_id varchar(64) not null references public."user"(user_id) on delete cascade,
  parent_id integer references public.user_comment(comment_id) on delete set null,
  body text not null,
  is_deleted boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists idx_user_comment_feed_id on public.user_comment(feed_id);
create index if not exists idx_user_comment_user_id on public.user_comment(user_id);
create index if not exists idx_user_comment_parent_id on public.user_comment(parent_id);

create table if not exists public.course (
  course_id integer generated by default as identity primary key,
  slug varchar(80) not null unique,
  title varchar(120) not null,
  mood varchar(20) not null,
  duration varchar(40) not null,
  note varchar(255) not null,
  color varchar(20) not null,
  display_order integer not null default 0
);
create index if not exists idx_course_display_order on public.course(display_order);

create table if not exists public.course_place (
  course_place_id integer generated by default as identity primary key,
  course_id integer not null references public.course(course_id),
  position_id integer not null references public.map(position_id),
  stop_order integer not null,
  constraint uq_course_place unique (course_id, position_id)
);
create index if not exists idx_course_place_stop_order on public.course_place(course_id, stop_order);

create table if not exists public.user_route (
  route_id integer generated by default as identity primary key,
  user_id varchar(64) not null references public."user"(user_id) on delete cascade,
  travel_session_id integer references public.travel_session(travel_session_id) on delete set null,
  title varchar(120) not null,
  description varchar(255) not null,
  mood varchar(20) not null,
  is_public boolean not null default true,
  is_user_generated boolean not null default false,
  like_count integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists idx_user_route_user_id on public.user_route(user_id);
create index if not exists idx_user_route_travel_session_id on public.user_route(travel_session_id);
create index if not exists idx_user_route_public_sort on public.user_route(is_public, like_count, created_at);

create table if not exists public.user_route_place (
  user_route_place_id integer generated by default as identity primary key,
  route_id integer not null references public.user_route(route_id) on delete cascade,
  position_id integer not null references public.map(position_id),
  stop_order integer not null,
  created_at timestamptz not null default now(),
  constraint uq_user_route_place unique (route_id, position_id)
);
create index if not exists idx_user_route_place_stop_order on public.user_route_place(route_id, stop_order);

create table if not exists public.user_route_like (
  route_like_id integer generated by default as identity primary key,
  route_id integer not null references public.user_route(route_id) on delete cascade,
  user_id varchar(64) not null references public."user"(user_id) on delete cascade,
  created_at timestamptz not null default now(),
  constraint uq_user_route_like unique (route_id, user_id)
);
create index if not exists idx_user_route_like_user_id on public.user_route_like(user_id);