import { updateMapViewportInUrl } from './useAppRouteState';
import type { useAppShellCoordinator } from './useAppShellCoordinator';

type AppShellCoordinatorState = ReturnType<typeof useAppShellCoordinator>;

export function useAppStageProps(state: AppShellCoordinatorState) {
  const {
    activeTab,
    sessionUser,
    handleOpenGlobalNotification,
    handleMarkAllNotificationsRead,
    handleDeleteNotification,
    activeCategory,
    setActiveCategory,
    selectedRoutePreview,
    currentPosition,
    mapLocationStatus,
    mapLocationFocusKey,
    stampActionStatus,
    stampActionMessage,
    reviewSubmitting,
    reviewError,
    feedPlaceFilterId,
    reviews,
    reviewLikeUpdatingId,
    commentSubmittingReviewId,
    commentMutatingId,
    deletingReviewId,
    activeCommentReviewId,
    highlightedCommentId,
    highlightedReviewId,
    feedHasMore,
    feedLoadingMore,
    courses,
    communityRoutes,
    communityRouteSort,
    routeLikeUpdatingId,
    highlightedRouteId,
    providers,
    myPageError,
    myPageTab,
    isLoggingOut,
    profileSaving,
    profileError,
    routeSubmitting,
    routeError,
    adminSummary,
    adminBusyPlaceId,
    adminLoading,
    myCommentsHasMore,
    myCommentsLoadingMore,
    loadMoreFeedReviews,
    loadMoreMyComments,
    activeReviewCommentsState,
    reviewActions,
    routeActions,
    adminActions,
    mapStageActions,
    pageStageActions,
    startProviderLogin,
    handleUpdateProfile,
    handleLogout,
    setMyPageTab,
    festivals,
    selectedPlaceReviews,
    viewModels,
    initialMapViewport,
    shellNavigation: {
      canNavigateBack,
      handleNavigateBack,
      handleBottomNavChange,
    },
  } = state;

  const {
    hydratedMyPage,
    globalStatus,
  } = viewModels;

  const mapStageProps = {
    mapData: {
      activeCategory,
      filteredPlaces: viewModels.filteredPlaces,
      festivals,
      selectedPlace: viewModels.selectedPlace,
      selectedFestival: viewModels.selectedFestival,
      currentPosition,
      mapLocationStatus,
      mapLocationFocusKey,
      drawerState: state.drawerState,
      sessionUser,
      selectedPlaceReviews,
      routePreview: selectedRoutePreview,
      routePreviewPlaces: viewModels.routePreviewPlaces,
      visitCount: viewModels.visitCount,
      latestStamp: viewModels.latestStamp,
      todayStamp: viewModels.todayStamp,
      stampActionStatus,
      stampActionMessage,
      reviewProofMessage: viewModels.reviewProofMessage,
      reviewError,
      reviewSubmitting,
      canCreateReview: viewModels.canCreateReview,
      hasCreatedReviewToday: viewModels.hasCreatedReviewToday,
      initialMapViewport,
    },
    mapActions: {
      setActiveCategory,
      onOpenPlaceFeed: mapStageActions.handleMapOpenPlaceFeed,
      onOpenPlace: mapStageActions.handleMapOpenPlace,
      onOpenRoutePreviewPlace: mapStageActions.handleMapOpenRoutePreviewPlace,
      onOpenFestival: mapStageActions.handleMapOpenFestival,
      onCloseDrawer: state.closeDrawer,
      onClearRoutePreview: mapStageActions.handleClearRoutePreview,
      onExpandPlaceDrawer: mapStageActions.handleExpandPlaceDrawer,
      onCollapsePlaceDrawer: mapStageActions.handleCollapsePlaceDrawer,
      onExpandFestivalDrawer: mapStageActions.handleExpandFestivalDrawer,
      onCollapseFestivalDrawer: mapStageActions.handleCollapseFestivalDrawer,
      onRequestLogin: mapStageActions.handleRequestLogin,
      onClaimStamp: state.handleClaimStamp,
      onCreateReview: reviewActions.handleCreateReview,
      onLocateCurrentPosition: mapStageActions.handleLocateCurrentPosition,
      onMapViewportChange: updateMapViewportInUrl,
    },
  };

  const pageStageProps = {
    activeTab: activeTab as Exclude<AppShellCoordinatorState['activeTab'], 'map'>,
    sharedData: {
      sessionUser,
      placeNameById: viewModels.placeNameById,
      festivals,
    },
    feedData: {
      reviews,
      reviewLikeUpdatingId,
      feedPlaceFilterId,
      commentSubmittingReviewId,
      commentMutatingId,
      deletingReviewId,
      activeCommentReviewId,
      activeCommentReviewComments: activeReviewCommentsState.activeReviewComments,
      activeCommentReviewStatus: activeReviewCommentsState.activeReviewCommentsStatus,
      highlightedCommentId,
      highlightedReviewId,
      feedHasMore,
      feedLoadingMore,
    },
    courseData: {
      courses,
      communityRoutes,
      communityRouteSort,
      routeLikeUpdatingId,
      highlightedRouteId,
    },
    myPageData: {
      myPage: hydratedMyPage,
      providers,
      myPageError,
      myPageTab,
      isLoggingOut,
      profileSaving,
      profileError,
      routeSubmitting,
      routeError,
      adminSummary,
      adminBusyPlaceId,
      adminLoading,
      commentsHasMore: myCommentsHasMore,
      commentsLoadingMore: myCommentsLoadingMore,
    },
    sharedActions: {
      onRequestLogin: mapStageActions.handleRequestLogin,
      onOpenPlace: state.handleOpenPlaceWithReturn,
    },
    feedActions: {
      onLoadMoreFeed: loadMoreFeedReviews,
      onToggleReviewLike: reviewActions.handleToggleReviewLike,
      onCreateComment: reviewActions.handleCreateComment,
      onUpdateComment: reviewActions.handleUpdateComment,
      onDeleteComment: reviewActions.handleDeleteComment,
      onDeleteReview: reviewActions.handleDeleteReview,
      onClearPlaceFilter: pageStageActions.handleClearPlaceFilter,
      onOpenComments: state.handleOpenReviewComments,
      onCloseComments: state.handleCloseReviewComments,
    },
    courseActions: {
      onChangeRouteSort: pageStageActions.handleChangeRouteSort,
      onToggleRouteLike: routeActions.handleToggleRouteLike,
      onOpenRoutePreview: state.handleOpenRoutePreview,
    },
    myPageActions: {
      onChangeMyPageTab: setMyPageTab,
      onLogin: startProviderLogin,
      onRetryMyPage: pageStageActions.handleRetryMyPage,
      onLogout: handleLogout,
      onSaveNickname: handleUpdateProfile,
      onPublishRoute: routeActions.handlePublishRoute,
      onOpenCommentFromMyPage: pageStageActions.handleOpenCommentFromMyPage,
      onOpenRouteFromMyPage: pageStageActions.handleOpenRouteFromMyPage,
      onOpenReview: state.handleOpenReviewWithReturn,
      onUpdateReview: reviewActions.handleUpdateReview,
      onDeleteReview: reviewActions.handleDeleteReview,
      onLoadMoreComments: loadMoreMyComments,
      onRefreshAdmin: adminActions.handleRefreshAdminImport,
      onToggleAdminPlace: adminActions.handleToggleAdminPlace,
      onToggleAdminManualOverride: adminActions.handleToggleAdminManualOverride,
    },
  };

  return {
    activeTab,
    canNavigateBack,
    handleNavigateBack,
    handleBottomNavChange,
    globalStatus,
    hydratedMyPage,
    sessionUser,
    handleOpenGlobalNotification,
    handleMarkAllNotificationsRead,
    handleDeleteNotification,
    mapStageProps,
    pageStageProps,
  };
}
