import type { useAppShellCoordinator } from './useAppShellCoordinator';

type AppShellCoordinatorState = ReturnType<typeof useAppShellCoordinator>;

export function usePageStageProps(state: AppShellCoordinatorState) {
  const {
    activeTab,
    activeCommentReviewId,
    activeReviewCommentsState,
    adminActions,
    adminBusyPlaceId,
    adminLoading,
    adminSummary,
    commentMutatingId,
    commentSubmittingReviewId,
    communityRouteSort,
    communityRoutes,
    courses,
    deletingReviewId,
    feedHasMore,
    feedLoadingMore,
    feedPlaceFilterId,
    festivals,
    handleOpenPlaceWithReturn,
    handleOpenReviewComments,
    handleOpenReviewWithReturn,
    highlightedCommentId,
    highlightedReviewId,
    highlightedRouteId,
    isLoggingOut,
    loadMoreFeedReviews,
    loadMoreMyComments,
    mapStageActions,
    myCommentsHasMore,
    myCommentsLoadingMore,
    myPageError,
    myPageTab,
    pageStageActions,
    profileError,
    profileSaving,
    providers,
    reviewActions,
    reviewLikeUpdatingId,
    reviews,
    routeActions,
    routeError,
    routeLikeUpdatingId,
    routeSubmitting,
    sessionUser,
    setMyPageTab,
    viewModels,
  } = state;

  return {
    activeTab: activeTab as Exclude<AppShellCoordinatorState['activeTab'], 'map'>,
    sharedData: {
      sessionUser,
      placeNameById: viewModels.placeNameById,
      festivals,
    },
    feedData: {
      reviews,
      reviewLikeUpdatingId,
      feedPlaceFilterId,
      commentSubmittingReviewId,
      commentMutatingId,
      deletingReviewId,
      activeCommentReviewId,
      activeCommentReviewComments: activeReviewCommentsState.activeReviewComments,
      activeCommentReviewStatus: activeReviewCommentsState.activeReviewCommentsStatus,
      highlightedCommentId,
      highlightedReviewId,
      feedHasMore,
      feedLoadingMore,
    },
    courseData: {
      courses,
      communityRoutes,
      communityRouteSort,
      routeLikeUpdatingId,
      highlightedRouteId,
    },
    myPageData: {
      myPage: viewModels.hydratedMyPage,
      providers,
      myPageError,
      myPageTab,
      isLoggingOut,
      profileSaving,
      profileError,
      routeSubmitting,
      routeError,
      adminSummary,
      adminBusyPlaceId,
      adminLoading,
      commentsHasMore: myCommentsHasMore,
      commentsLoadingMore: myCommentsLoadingMore,
    },
    sharedActions: {
      onRequestLogin: mapStageActions.handleRequestLogin,
      onOpenPlace: handleOpenPlaceWithReturn,
    },
    feedActions: {
      onLoadMoreFeed: loadMoreFeedReviews,
      onToggleReviewLike: reviewActions.handleToggleReviewLike,
      onCreateComment: reviewActions.handleCreateComment,
      onUpdateComment: reviewActions.handleUpdateComment,
      onDeleteComment: reviewActions.handleDeleteComment,
      onDeleteReview: reviewActions.handleDeleteReview,
      onClearPlaceFilter: pageStageActions.handleClearPlaceFilter,
      onOpenComments: handleOpenReviewComments,
      onCloseComments: state.handleCloseReviewComments,
    },
    courseActions: {
      onChangeRouteSort: pageStageActions.handleChangeRouteSort,
      onToggleRouteLike: routeActions.handleToggleRouteLike,
      onOpenRoutePreview: state.handleOpenRoutePreview,
    },
    myPageActions: {
      onChangeMyPageTab: setMyPageTab,
      onLogin: state.startProviderLogin,
      onRetryMyPage: pageStageActions.handleRetryMyPage,
      onLogout: state.handleLogout,
      onSaveNickname: state.handleUpdateProfile,
      onPublishRoute: routeActions.handlePublishRoute,
      onOpenCommentFromMyPage: pageStageActions.handleOpenCommentFromMyPage,
      onOpenRouteFromMyPage: pageStageActions.handleOpenRouteFromMyPage,
      onOpenReview: handleOpenReviewWithReturn,
      onUpdateReview: reviewActions.handleUpdateReview,
      onDeleteReview: reviewActions.handleDeleteReview,
      onLoadMoreComments: loadMoreMyComments,
      onRefreshAdmin: adminActions.handleRefreshAdminImport,
      onToggleAdminPlace: adminActions.handleToggleAdminPlace,
      onToggleAdminManualOverride: adminActions.handleToggleAdminManualOverride,
    },
  };
}
