create table if not exists public.user_notification (
  notification_id integer generated by default as identity primary key,
  user_id varchar(64) not null references public."user"(user_id) on delete cascade,
  actor_user_id varchar(64) references public."user"(user_id) on delete set null,
  type varchar(30) not null,
  title varchar(120) not null,
  body varchar(255) not null default '',
  review_id integer references public.feed(feed_id) on delete cascade,
  comment_id integer references public.user_comment(comment_id) on delete cascade,
  route_id integer,
  is_read boolean not null default false,
  read_at timestamptz,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_user_notification_user_created_at
  on public.user_notification(user_id, created_at desc);

create index if not exists idx_user_notification_user_is_read
  on public.user_notification(user_id, is_read);
