-- 2026-03-18: stamp log / travel session / proof-of-visit normalization
-- Goals:
-- 1. Convert user_stamp from a boolean-style visit marker into a visit log table.
-- 2. Add travel_session as the grouping unit for stamps collected within 24 hours.
-- 3. Require stamp_id on feed so review creation always has proof of visit.
-- 4. Add travel_session_id and is_user_generated to user_route.
-- 5. Add profile_completed_at for nickname completion after OAuth.

alter table public."user"
  add column if not exists profile_completed_at timestamptz;

drop index if exists idx_user_provider;
create index if not exists idx_user_provider on public."user"(provider);

create table if not exists public.travel_session (
  travel_session_id integer generated by default as identity primary key,
  user_id varchar(64) not null references public."user"(user_id) on delete cascade,
  started_at timestamptz not null,
  ended_at timestamptz not null,
  last_stamp_at timestamptz not null,
  stamp_count integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists idx_travel_session_user_id on public.travel_session(user_id);
create index if not exists idx_travel_session_last_stamp_at on public.travel_session(last_stamp_at);

alter table public.user_stamp
  add column if not exists travel_session_id integer references public.travel_session(travel_session_id) on delete set null,
  add column if not exists stamp_date date,
  add column if not exists visit_ordinal integer not null default 1;

update public.user_stamp
set stamp_date = timezone('Asia/Seoul', created_at)::date
where stamp_date is null;

with ranked as (
  select
    stamp_id,
    row_number() over (
      partition by user_id, position_id
      order by created_at asc, stamp_id asc
    ) as visit_no
  from public.user_stamp
)
update public.user_stamp us
set visit_ordinal = ranked.visit_no
from ranked
where ranked.stamp_id = us.stamp_id;

alter table public.user_stamp
  drop constraint if exists uq_user_stamp;

drop index if exists uq_user_stamp_per_day;
create unique index if not exists uq_user_stamp_per_day
  on public.user_stamp(user_id, position_id, stamp_date);
create index if not exists idx_user_stamp_travel_session_id on public.user_stamp(travel_session_id);
create index if not exists idx_user_stamp_user_created_at on public.user_stamp(user_id, created_at);

alter table public.feed
  add column if not exists stamp_id integer references public.user_stamp(stamp_id);

update public.feed f
set stamp_id = (
  select us.stamp_id
  from public.user_stamp us
  where us.user_id = f.user_id
    and us.position_id = f.position_id
  order by us.created_at desc, us.stamp_id desc
  limit 1
)
where f.stamp_id is null;

alter table public.feed
  alter column badge set default 'Local memo';

create index if not exists idx_feed_stamp_id on public.feed(stamp_id);

alter table public.user_route
  add column if not exists travel_session_id integer references public.travel_session(travel_session_id) on delete set null,
  add column if not exists is_user_generated boolean not null default false;
create index if not exists idx_user_route_travel_session_id on public.user_route(travel_session_id);

alter table public.public_event
  alter column district set default '';