PLACE_SEEDS = [
    {
        "slug": "hanbat-forest",
        "name": "한밭수목원 잼가든",
        "district": "서구",
        "category": "landmark",
        "latitude": 36.3671,
        "longitude": 127.3886,
        "summary": "산책만 해도 사진이 예쁘게 나오는 대전 대표 힐링 코스",
        "description": "커다란 온실과 계절 꽃길이 이어져서 첫 방문자도 부담 없이 즐길 수 있어요. 텍스트보다 장면이 먼저 기억나는 장소라 메인 랜딩 포인트로 좋아요.",
        "vibe_tags": ["꽃길", "피크닉", "산책"],
        "visit_time": "40분 - 1시간 20분",
        "route_hint": "엑스포다리와 함께 묶으면 노을 코스 완성",
        "stamp_reward": "꽃잼 스티커 잠금 해제",
        "hero_label": "Bloom Spot",
        "jam_color": "#ff7aab",
        "accent_color": "#8fd7ff",
    },
    {
        "slug": "expo-bridge",
        "name": "엑스포다리 선셋뷰",
        "district": "유성구",
        "category": "night",
        "latitude": 36.3765,
        "longitude": 127.3868,
        "summary": "노을과 강바람을 함께 즐기는 데이트 마커",
        "description": "해가 내려갈 때 조명이 켜지며 분위기가 확 달라져요. 사진, 산책, 짧은 대화가 모두 가능한 저녁 코스로 추천해요.",
        "vibe_tags": ["노을", "데이트", "야경"],
        "visit_time": "30분 - 50분",
        "route_hint": "한밭수목원에서 이동하면 저녁 코스로 매끄러워요",
        "stamp_reward": "선셋잼 리본 획득",
        "hero_label": "Sunset Spot",
        "jam_color": "#ff5f8f",
        "accent_color": "#7e9dff",
    },
    {
        "slug": "sungsimdang-culture",
        "name": "성심당 문화원 골목",
        "district": "중구",
        "category": "food",
        "latitude": 36.3276,
        "longitude": 127.4271,
        "summary": "빵만이 아니라 대전 감성을 함께 묶어 보여주는 중심 축",
        "description": "유명세를 외면하지 않되, 주변 골목과 로컬 스팟을 함께 묶어서 성심당만 있는 도시라는 인식을 넓히는 허브로 설계했어요.",
        "vibe_tags": ["빵투어", "로컬", "핵심거점"],
        "visit_time": "30분 - 1시간",
        "route_hint": "은행동 골목과 연계하면 체류 시간이 자연스럽게 늘어요",
        "stamp_reward": "버터잼 배지 획득",
        "hero_label": "Bread Hub",
        "jam_color": "#ff8d63",
        "accent_color": "#ffcf69",
    },
    {
        "slug": "dunsan-photo",
        "name": "둔산 소품샵 라인",
        "district": "서구",
        "category": "cafe",
        "latitude": 36.3514,
        "longitude": 127.3782,
        "summary": "아기자기한 사진과 카페 탐색을 한 번에 즐기는 구간",
        "description": "짧은 동선 안에 카페, 편집숍, 포토 스팟이 이어져서 계획형 사용자에게 특히 잘 맞아요. 지도에서 여러 곳을 빠르게 비교하기 좋은 영역이에요.",
        "vibe_tags": ["소품샵", "포토존", "카페"],
        "visit_time": "1시간 - 2시간",
        "route_hint": "비 오는 날 실내 코스로도 전환이 쉬워요",
        "stamp_reward": "솜사탕잼 프레임 지급",
        "hero_label": "Cute Loop",
        "jam_color": "#ff9fd0",
        "accent_color": "#91a7ff",
    },
    {
        "slug": "daecheong-lake",
        "name": "대청호 레이크뷰",
        "district": "동구",
        "category": "landmark",
        "latitude": 36.4803,
        "longitude": 127.4784,
        "summary": "도시에서 조금 벗어나 탁 트인 장면을 보는 리프레시 포인트",
        "description": "드라이브나 짧은 외곽 코스를 찾는 사람에게 어울려요. 대전을 머물기 좋은 도시로 느끼게 하는 장면형 장소라 확장성도 높아요.",
        "vibe_tags": ["드라이브", "호수", "힐링"],
        "visit_time": "1시간 - 2시간",
        "route_hint": "오후 출발 반나절 코스로 구성하기 좋아요",
        "stamp_reward": "라군잼 배경 지급",
        "hero_label": "Lake Escape",
        "jam_color": "#8bc8ff",
        "accent_color": "#7ce0cf",
    },
    {
        "slug": "galleria-rooftop",
        "name": "갈마 루프탑 디저트",
        "district": "서구",
        "category": "food",
        "latitude": 36.3487,
        "longitude": 127.3725,
        "summary": "가볍게 들러도 만족도가 높은 디저트 앵커",
        "description": "짧은 체류에도 분위기가 살아서 일정 사이사이에 넣기 좋아요. 메인 여정의 휴식 포인트이자 사진용 카드로 활용하기 좋은 장소예요.",
        "vibe_tags": ["디저트", "루프탑", "휴식"],
        "visit_time": "20분 - 40분",
        "route_hint": "둔산 소품샵 라인과 함께 묶으면 밀도 높은 반나절 코스",
        "stamp_reward": "살구잼 토스트 획득",
        "hero_label": "Sweet Break",
        "jam_color": "#ffb158",
        "accent_color": "#ff7fa3",
    },
]

USER_SEEDS = [
    {"user_id": "jam-demo-user", "nickname": "소희", "email": "sohee@example.com", "provider": "demo"},
    {"user_id": "user-minji", "nickname": "민지", "email": "minji@example.com", "provider": "seed"},
    {"user_id": "user-jiyoon", "nickname": "지윤", "email": "jiyoon@example.com", "provider": "seed"},
    {"user_id": "user-seoa", "nickname": "서아", "email": "seoa@example.com", "provider": "seed"},
    {"user_id": "user-yujin", "nickname": "유진", "email": "yujin@example.com", "provider": "seed"},
]

REVIEW_SEEDS = [
    {"slug": "hanbat-forest", "user_id": "user-minji", "body": "꽃길 따라 걷다가 바로 사진 찍기 좋아요. 글 길게 안 읽어도 앱 카드만 보고 이동했는데 만족했어요.", "mood": "설렘", "badge": "첫 방문"},
    {"slug": "expo-bridge", "user_id": "user-jiyoon", "body": "노을 시간 추천해준 게 진짜 좋았어요. 다리 위에서 바람 쐬고 바로 카페로 이동하기 딱이었어요.", "mood": "야경픽", "badge": "데이트 성공"},
    {"slug": "dunsan-photo", "user_id": "user-seoa", "body": "카테고리만 눌러도 취향 맞는 곳이 보여서 편했어요. 사진 스팟만 빠르게 고르기 좋았습니다.", "mood": "친구랑", "badge": "포토러버"},
    {"slug": "sungsimdang-culture", "user_id": "user-yujin", "body": "빵만 찍고 끝나는 느낌이 아니라 주변 골목까지 같이 보는 동선이 괜찮았어요.", "mood": "혼자서", "badge": "로컬탐방"},
]

COURSE_SEEDS = [
    {"slug": "course-date", "title": "노을 데이트 잼코스", "mood": "데이트", "duration": "3시간", "note": "산책 -> 디저트 -> 선셋까지 연결되는 가장 쉬운 입문 코스", "color": "#ff8ab1", "display_order": 1, "place_slugs": ["hanbat-forest", "galleria-rooftop", "expo-bridge"]},
    {"slug": "course-photo", "title": "사진 남기는 하루", "mood": "사진", "duration": "4시간", "note": "아기자기한 공간과 색감이 살아나는 장소를 우선 배치", "color": "#8db8ff", "display_order": 2, "place_slugs": ["dunsan-photo", "hanbat-forest", "sungsimdang-culture"]},
    {"slug": "course-healing", "title": "반나절 힐링 드라이브", "mood": "힐링", "duration": "4시간 30분", "note": "복잡한 도심을 벗어나고 싶을 때 선택하는 리프레시 루트", "color": "#7ddccf", "display_order": 3, "place_slugs": ["daecheong-lake", "hanbat-forest", "expo-bridge"]},
    {"slug": "course-rainy", "title": "비 오는 날 실내 픽", "mood": "비 오는 날", "duration": "2시간 30분", "note": "짧은 이동으로도 무드가 유지되는 실내 중심 플랜", "color": "#91a5ff", "display_order": 4, "place_slugs": ["dunsan-photo", "galleria-rooftop", "sungsimdang-culture"]},
]

DEFAULT_STAMP_SLUGS = ["hanbat-forest", "sungsimdang-culture"]
